#161290900 User reset password to account via email password reset
andela/noldor-ah-backend pull request #16
Opened 2018-11-07 10:59 UTC by anasey01

#### What does this PR do?
- Sends an email in HTML format to users on request for a password reset
- Issues users a valid token that lasts for an hour
- Ascertain a user's information before granting access to update a password
- Stores a copy of the token issued to the user in the database
- Validates user's input for an email address and password
- Refactored the user routes to avoid congestion 
- Tests the validity of the password reset functionality

#### Description of Task to be completed?
`/PUT 200 OK - /api/v1/users/forgot/`
-- Required field: `The user's valid email address that exists in the database`.
`/POST 200 OK - /api/v1/users/forgot/:hash`
-- Required fields: `password` and `confirmPassword`.

#### How should this be manually tested?
- After cloning this repo, cd into it and `run npm install` to install all the dependencies and dev-dependencies.
- Using the `.env.sample` content, create a `.env` in your root directory and fill in the fields.
- To run the test suit, run `npm run test-dev` script
- To run on the development mode, run `npm run dev` script

You can now go ahead to test the endpoints.

#### Any background context you want to provide?
- To get `SENDGRID_API_KEY`, you need to register on [sendgrid](https://www.sendgrid.com/) to get an API key and then insert the key as stated on .env.sample file

#### What are the relevant pivotal tracker stories?
#161290900
#### Screenshots (if appropriate)
<img width="1143" alt="screen shot 2018-11-07 at 11 52 49 am" src="https://user-images.githubusercontent.com/25327188/48127487-22ab1d00-e284-11e8-9370-1f996949c22b.png">

<img width="1142" alt="screen shot 2018-11-07 at 11 55 45 am" src="https://user-images.githubusercontent.com/25327188/48127501-2dfe4880-e284-11e8-960d-b6b919a6f5e5.png">

#### Questions:
N/A

2018-11-07 11:12 UTC, hope-uwa requested changes
please fix hound error. Nice job

2018-11-07 11:12 UTC, hope-uwa approved these changes

2018-11-07 11:17 UTC, ovieokeh approved these changes
Tested on my local machine and everything works as it should. Good job.

2018-11-09 17:20 UTC, desaawa approved these changes
lgtm. Please resolve merge conflicts.

2018-11-12 10:02 UTC, merged