#161290898 Signup Verification Email
andela/noldor-ah-backend pull request #34
Opened 2018-11-19 00:55 UTC by ajimae

#### What does this PR do?
 Enable users to receive a welcome message and an email verification link on successful registration

#### Description of Task to be completed?

- Modify migration and user model files to accommodate emailVerificationHash column
- Write functions that will enable users receive a verification link on successful registration
- Add a middleware script to check email/account verification status
- Write test to validate functionality when user is verified or unverified
- Refactor email library from sendGrid to nodemailer
- Refactor email template to comply with the team accepted format
- Write a function to update the database on successful email verification
- Write tests to validate email/account verification functionality

#### How should this be manually tested?

- Clone the repo
- Run `npm install` to install dependencies and devDependencies
- Run Postma, using the `POST` verb visit the address `localhost:3000/api/v1/users/register` to register an account
- If step 3 above is successful login to the provided email address and copy the link linked to the button and paste in Postman, using the `GET` verb click on send

#### Any background context you want to provide?

- A valid email and password may be provided in the env variables to be able to use the emailing services.

#### What are the relevant pivotal tracker stories?

[#161290898](https://www.pivotaltracker.com/story/show/161290898)

#### Screenshots

<img width="860" alt="screen shot 2018-11-19 at 1 52 57 am" src="https://user-images.githubusercontent.com/32770340/48680701-e9d14900-eb9d-11e8-9f10-03b479ddcf73.png">

2018-11-19 07:34 UTC, 65black commented on server/src/controllers/UserController.js
> +              message: 'Registration successful',
I thought we were using all lowercase for the response messages?

2018-11-19 07:35 UTC, 65black commented on server/src/db/migrations/a-create-user.js
> +  if (process.env.NODE_ENV === 'test') {
Perfect idea Chukwuemeka!!

2018-11-19 07:35 UTC, ovieokeh approved these changes
I've gone through all the files changed. Awesome work!

2018-11-19 09:17 UTC, anasey01 commented on server/src/db/migrations/a-create-user.js
> +  if (process.env.NODE_ENV === 'test') {
This is amazing @ajimae. Great Job!

2018-11-19 09:21 UTC, oluseyianani approved these changes
Changes look good. Nodemailer works better than sendgrid API after much email blasts.

2018-11-19 19:44 UTC, awadesmoline commented
Please resolve conflicts and failing tests

2018-11-20 12:13 UTC, hope-uwa requested changes
@ajimae Great job on integrating nodemailer for sending emails. I noticed you disabled Airbnb eslint console.log rule on some lines in the sendMail.js file. I believe its best practice that console shouldn’t be allowed on production code. The nodemailer errors displayed during the tests makes the test buggy and hard to read. I think you can capture the errors some other way, for example by logging it to a text file. Thanks.

2018-11-20 15:51 UTC, 65black commented on server/src/helpers/articleRatings.js
> +    }).then((data) => {
To solve this issue, just remove the `{ return` part of `.then` segment. Plus the merge conflicts and other Hound CI errors should also be rectified.

2018-11-21 10:20 UTC, hope-uwa approved these changes

2018-11-22 13:55 UTC, desaawa approved these changes

2018-11-22 13:55 UTC, merged