#162235639 Authenticate User Middleware
andela/noldor-ah-backend pull request #46
Opened 2018-11-27 15:35 UTC by anasey01

#### What does this PR do?
- Validates that users with token actually exists in the database
- Works on test cases to make sure they return the right message and status codes
- Adjust affected functionality to ensure test case passes.

#### Description of Task to be completed?
Ensures that all users with token are checked against the database to ensure they exist.

#### How should this be manually tested?
A deleted user can no longer have access to the platform even if the right token is provided.

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
#162235639

#### Screenshots (if appropriate)
<img width="1067" alt="screen shot 2018-11-27 at 4 34 30 pm" src="https://user-images.githubusercontent.com/25327188/49092444-5ca78780-f262-11e8-9852-4cf6ab1bf3bc.png">

#### Questions:
N/A

2018-11-27 18:52 UTC, ajimae requested changes
Awesome work @anasey01, now we don't have to worry about the Sequelize/PostgreSQL database errors anymore.
One more thing, please fix the 4 hounds violations.

Thank you.

2018-11-28 08:22 UTC, ovieokeh requested changes
You shouldn't have raised this PR with so many errors. Fix them now!

2018-11-28 13:45 UTC, hope-uwa approved these changes
looks good @anasey01

2018-12-03 10:33 UTC, ajimae approved these changes

2018-12-03 10:34 UTC, ovieokeh approved these changes

2018-12-03 10:42 UTC, merged