#161290919 Users Reading Stats
andela/noldor-ah-backend pull request #48
Opened 2018-11-28 13:28 UTC by ajimae

#### What does this PR do?
 Enable users to see their reading statistics

#### Description of Task to be completed?

- Write test
- Add a migration script to create a ReadingStats table
- Add a model 
- Write functions to post reading statistics to the ReadingStats table
- Write tests to validate functionality
- Create a route to handle route users get reading statistics requests
- Write functions to get users reading statistics
- Validate functionality in Postman

#### How should this be manually tested?

- Clone the repo to local machine
- Run `npm install` to install dependencies and devDependencies
- Run Postma, using the `POST` verb visit the address `localhost:3000/api/v1/users/register` to register an account
- Visit `localhost:3000/api/v1/articles` provide the necessary request body to post an article using `POST`
- Get an article by visiting the `URL` `localhost:3000/api/v1/articles` using `GET`

#### Any background context you want to provide?

- Modified the `Procfile` to drop all database tables on before each build.
- Refactored the `verificationWorker.js` file

#### What are the relevant pivotal tracker stories?

[#161290919](https://www.pivotaltracker.com/story/show/161290919)

#### Screenshots

<img width="1131" alt="screen shot 2018-11-28 at 2 26 45 pm" src="https://user-images.githubusercontent.com/32770340/49154815-b7e88100-f319-11e8-979b-123794cf1744.png">

2018-11-29 10:06 UTC, hope-uwa requested changes
@ajimae I noticed this PR does more than just implementing the Users Reading stat. Please state the other things it does in the PR description, example the bug fix for verification middleware. And also noticed some spelling errors in ReadingStatsWorker on ln13 and ln39.


Thanks so much for your observation, feedback was well received @uwaelpis, also, please you are not specific enough. Where (on what file) did you see the spelling errors? and besides the changes on the `verificationWorker.js` wasn't a bug fix it was a minor refactor. Also as a feedback, I suggest you pay more attention to details and understand what is going on before you comment. Thanks once again. Please direct me to where the spelling errors are, so I can make the necessary changes.

2018-11-29 10:51 UTC, uwaelpis commented on server/src/workers/ReadingStatsWorker.js
> +class ReadingSatsWorker {
I guess you meant to spell ReadingStatsWorker

2018-11-29 10:52 UTC, uwaelpis commented on server/src/workers/ReadingStatsWorker.js
> +  static async getUserRedingStats(userId, res) {
and here too

2018-11-29 10:58 UTC, uwaelpis commented
@ajimae Thanks for the feedback, You should have captured the minor refactoring done in your PR description because I see a lot of file changes that are not reflected in the description

2018-11-29 11:22 UTC, ajimae commented on server/src/workers/ReadingStatsWorker.js
> +class ReadingSatsWorker {
Done.
Thanks for pointing it out.

2018-11-29 11:23 UTC, ajimae commented on server/src/workers/ReadingStatsWorker.js
> +  static async getUserRedingStats(userId, res) {
Done.
Thanks for pointing it out also.

2018-11-29 12:14 UTC, hope-uwa approved these changes

2018-11-29 12:15 UTC, uwaelpis commented
Great job!

2018-12-03 11:12 UTC, ovieokeh approved these changes

2018-12-03 11:14 UTC, merged